### ISSUE TITLE
.ackrc

### ISSUE THREAD

**Issue by jojomi** [monochromegane/the_platinum_searcher#102]
Ack uses a file called .ackrc for defining default settings for a project or a user.
It supports (almost) all command line switches.

Did I miss something or is this a feature not implemented in pt yet?

**Comment by monochromegane** [comment]
The feature is scheduled to implement in the near future :)
I have already implemented [conflag](https://github.com/monochromegane/conflag) package for the feature.
Please wait a little longer :smiley:

**Comment by monochromegane** [comment]
I released this feature at v1.7.9.
If you put `.ptconfig.toml` on $HOME or current directory, pt use options as default.
Please check it :beers:
