### ISSUE TITLE
Cannot specify multiple ignores in ptconfig.toml

### ISSUE THREAD

**Issue by einars** [monochromegane/the_platinum_searcher#107]
It looks like it's impossible to specify multiple ignores in the global configuration, ~/.ptconfig.toml

A single value works:

      ignore = "node_modules"

      % pt
      ...
      --ignore=             Ignore files/directories matching pattern (default: [node_modules])

This ignores the ignores completely:

      ignore = "third_party"
      ignore = "node_modules"

      % pt
      ...
      --ignore=             Ignore files/directories matching pattern

And this ignores the ignores completely in a different way, notice the double-list:

      ignore = ["third_party", "node_modules"]

      % pt
      ...
      --ignore=             Ignore files/directories matching pattern (default: [[third-party node_modules]])

(v1.7.9 under archlinux, built from aur)

**Comment by monochromegane** [comment]
Thanks for reporting.
ptconfig use [conflag](https://travis-ci.org/monochromegane/conflag), and support multiple parameters now.
So, conflag can specify list by the following.

```toml
ignore = ["third_party", "node_modules"]
```

If you use the_platinum_searcher by `go get`, you can update `conflag`. (`go get github.com/monochromegane/conflag`) and re-build pt.
If you use homebrew or binary, I will release new version in December. Please wait :^)

**Comment by einars** [comment]
Terrific, it works as a charm!
