### ISSUE TITLE
Solaris support

### ISSUE THREAD

**Issue by klauern** [monochromegane/the_platinum_searcher#111]
I am working with a Solaris box and I wanted to use this tool, but found no equivalent release version.  I tried building this myself, but I suspect that monochromegane/terminal#2 issue is probably causing it to fail on my end.

**Comment by monochromegane** [comment]
Hi, I have merged https://github.com/monochromegane/terminal/pull/3 now.
Please try update terminal package, and build on your Solaris :smile:
