### ISSUE TITLE
The readme is not easy for beginners to configure in Vim + Unite part

### ISSUE THREAD

**Issue by HackToday** [monochromegane/the_platinum_searcher#112]
I have followed this guide and check 

Vim + Unite.vim

You can use pt with Unite.vim.

nnoremap <silent> ,g :<C-u>Unite grep:. -buffer-name=search-buffer<CR>
if executable('pt')
  let g:unite_source_grep_command = 'pt'
  let g:unite_source_grep_default_opts = '--nogroup --nocolor'
  let g:unite_source_grep_recursive_opt = ''
  let g:unite_source_grep_encoding = 'utf-8'
endif

Unite is easy to install with bundle.

After that, I tried the install the https://github.com/monochromegane/the_platinum_searcher/releases
and tar -zxvf **, and configure pt in $PATH,

But I add following:
nnoremap <silent> ,g :<C-u>Unite grep:. -buffer-name=search-buffer<CR>
if executable('pt')
  let g:unite_source_grep_command = 'pt'
  let g:unite_source_grep_default_opts = '--nogroup --nocolor'
  let g:unite_source_grep_recursive_opt = ''
  let g:unite_source_grep_encoding = 'utf-8'
endif

to .vimrc,  and I use Ctrl+u, or :Unite grep cli
both can not work,  I did not quite undestand how to configure it work with Unite

**Comment by monochromegane** [comment]
I think you must get [vimproc.vim](https://github.com/Shougo/vimproc.vim) that is `interactive command execution in Vim.`

Add the line in you .vimrc, and `:BundleInstall`

```
Bundle "git://github.com/Shougo/vimproc" 
```

And compile vimproc.

```
$ cd ~/.vim/bundle/vimproc
$ make_mac.mak # If you use OSX. You must select file for your platform.
```

Thank you for reporting.

**Comment by HackToday** [comment]
hi @monochromegane thanks, yes it was because of that.

**Comment by monochromegane** [comment]
:smiley:
