### ISSUE TITLE
can't see the match result clearly on windows

### ISSUE THREAD

**Issue by wuqi** [monochromegane/the_platinum_searcher#117]
Sorry for my poor english.

In decorator.go,the match color is  \x1b[30;43m  ,on windows it's all like yellow and grey color 
so I suggest change it to \x1b[34;47m blue with white background,like in ack2.

And another suggestion : use chardet lib to detect encoding.

**Comment by monochromegane** [comment]
Hi @wuqi .
I have released v2.1.0 now that contains `color-line-number`, `color-path` and `color-match` options.

You can specify the options like the following:

```sh
$ pt --color-path="1;34" PATTERN
```

and you can add the same option in .ptconfig.toml :smile: 

see also: https://github.com/monochromegane/the_platinum_searcher/pull/130

Thanks.
