### ISSUE TITLE
Special characters from locale codepage not found.

### ISSUE THREAD

**Issue by vovcacik** [monochromegane/the_platinum_searcher#119]
When I search for special character from Czech alphabet, `pt` returns no results.

Example:
```
chcp 1250
echo This line should match: česky>match.txt

rem pt gives no output
pt česky

rem sift gives no output
sift česky

rem grep works
grep česky *

rem ag works
ag česky
```
See also svent/sift#59

**Comment by StefanSchroeder** [comment]
So, what exactly is your encoding? The readme of pt states that: "pt searches UTF-8, EUC-JP and Shift_JIS files". Which of those three do you have?

**Comment by jschpp** [comment]
If I understand the above code correctly he is using Windows Codepage 1250. Which in my understanding is neither UTF-8, EUC-JP or Shift_JS.

**Comment by vovcacik** [comment]
@StefanSchroeder, @jschpp: Yeah, CP-1250. I wasn't aware of that pt only supports UTF-8, EUC-JP and Shift_JIS.
