### ISSUE TITLE
Multiple matches on the same line

### ISSUE THREAD

**Issue by juanibiapina** [monochromegane/the_platinum_searcher#120]
Is it on purpose that pt only gets the first match per line? Is there an option to search all matches?

**Comment by vovcacik** [comment]
Do you refer to count option `pt -c` or classic output? When I do normal search it will highlight all occurrences on a line, but count option does not count occurrences but only lines with occurrences -- which is wrong. Same issue?

**Comment by juanibiapina** [comment]
```
pt --nogroup --nocolor --column -i pattern
```

This command only shows the first match. I'm comparing with:

```
ag --vimgrep pattern
```

Which shows several occurrences on the same line.

**Comment by vovcacik** [comment]
I see, you want extra line in output for each occurrence, thats exactly what the `--vimgrep` is for, so it is intentional. The `-c` bug is different issue then.
