### ISSUE TITLE
Count option counts multiple matches on a line as a single match.

### ISSUE THREAD

**Issue by vovcacik** [monochromegane/the_platinum_searcher#121]
The `--count` option should count total number of **matches** in a file (*Only print the number of matches in each file.*), but it actually counts total number of **lines** with more than one match.

**Comment by jpcirrus** [comment]
And it increases the count by the number of lines of context, if any.

**Comment by vovcacik** [comment]
@jpcirrus nice catch, see #125 
@syohex thanks, that fixes this for me
