### ISSUE TITLE
Count option counts non matching context lines as matches.

### ISSUE THREAD

**Issue by vovcacik** [monochromegane/the_platinum_searcher#125]
When you specify non zero context option and count option together, the context lines are counted together with matches - the count function should ignore non matching context lines.

###### Test file:

```
foo
test
bar

foo
test
```

###### Result:

`pt -c test` returns 2
`pt -c -C 0 test` returns 2
`pt -c -C 1 test` returns 5 (adds first, third and fifth line)

**Comment by jpcirrus** [comment]
This has been fixed in 2.0.4. Many thanks.

**Comment by syohex** [comment]
@vovcacik Could you close this issue if you confirmed this issue is fixed ?

**Comment by vovcacik** [comment]
Fixed, thank you!
