### ISSUE TITLE
Install fail on 1.5.3

### ISSUE THREAD

**Issue by paulheideman** [monochromegane/the_platinum_searcher#131]
Not sure if this is a known issue or not.

Installing on go1.5.3 with Ubuntu 14.04 gives me:
```
$ go get -u github.com/monochromegane/the_platinum_searcher/...
package github.com/monochromegane/the_platinum_searcher
	imports runtime: C source files not allowed when not using cgo or SWIG: atomic_amd64x.c defs.c float.c heapdump.c lfstack.c malloc.c mcache.c mcentral.c mem_linux.c mfixalloc.c mgc0.c mheap.c msize.c os_linux.c panic.c parfor.c proc.c runtime.c signal.c signal_amd64x.c signal_unix.c stack.c string.c sys_x86.c vdso_linux_amd64.c
```

However it works fine on the same system with go1.4.3...

**Comment by syohex** [comment]
Please retry after removing old go(1.4.3).

See also
- http://stackoverflow.com/questions/32115229/go-1-5-error-imports-runtime-c-source-files-not-allowed-when-not-using-cgo-o

**Comment by paulheideman** [comment]
Yup, that solved it, thanks!
