### ISSUE TITLE
Is there any implementation of a pager?

### ISSUE THREAD

**Issue by district10** [monochromegane/the_platinum_searcher#136]
`ag` has a pager option so you can use `ag --pager=less keyword` to use `less` to browser all matches. Is this implemented in `pt`?

**Comment by imranismail** [comment]
I would like to know about this as well

**Comment by StefanSchroeder** [comment]
What's wrong with piping the result of pt through the pager of your choice?
pt ... | less

**Comment by district10** [comment]
@StefanSchroeder The coloring (of matched text) will be dropped if you just pipe the result into `less`.

**Comment by monochromegane** [comment]
@district10 Hi, I recommend you use piping.
If you want color and grouping into `less`, you can specify `--color`, `--group` option.
Their options always coloring, grouping.

```
pt --color --group PATTERN | less
```

**Comment by district10** [comment]
@monochromegane It works! Thank you.
