### ISSUE TITLE
Option to omit line numbers

### ISSUE THREAD

**Issue by fsouza** [monochromegane/the_platinum_searcher#138]
Using ``pt`` I missed the option to omit line numbers from the output. Would an option such as ``--no-line-number/-N`` be interesting? If so, I can prepare a patch.

Thanks for this great tool! :-)

**Comment by monochromegane** [comment]
Hi @fsouza! I'm interested in it.
I'm looking forward to your patch :-)

**Comment by monochromegane** [comment]
Hi, `--[no]number` and `-N` option has released now.
https://github.com/monochromegane/the_platinum_searcher/releases/tag/v2.1.4

Thanks @StefanSchroeder !
refs: https://github.com/monochromegane/the_platinum_searcher/pull/146
