### ISSUE TITLE
ptconfig について要望

### ISSUE THREAD

**Issue by 39e** [monochromegane/the_platinum_searcher#141]
`$HOME/.ptconfig.toml` と `$PWD/.ptconfig.toml` をサポートするとのことでしたが `$HOME` をドットファイルで汚したくないので XDG Base Directory Specification という仕様と同じように `$HOME/.config/pt/config.toml` もサポートして欲しいです。

**Comment by zonuexe** [comment]
XDG Base Directory Specificationに従うなら`$HOME/.config/pt/config.toml`ではなく`$XDG_CONFIG_HOME/pt/config.toml`ではないでしょうか

**Comment by 39e** [comment]
おっと typo でした、申し訳ございません

**Comment by monochromegane** [comment]
`$XDG_CONFIG_HOME`がある場合は、XDG Base Directory Specificationに従えるよう、 `$XDG_CONFIG_HOME/pt/config.toml` を参照するよう対応しました。
該当する環境変数のない場合は既存の挙動となります。

まだリリースは切っていないので、お手元でのビルドにてご確認ください。

**Comment by monochromegane** [comment]
v2.1.2 としてリリースしました
https://github.com/monochromegane/the_platinum_searcher/releases/tag/v2.1.2
