### ISSUE TITLE
XDG configuration file path implemented incorrectly

### ISSUE THREAD

**Issue by maletor** [monochromegane/the_platinum_searcher#156]
> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

cf. https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html

Therefore, a lookup path of 
1. `$XDG_CONFIG_HOME/pt/config.toml`
2. `$HOME/.ptconfig.toml`
3. `./.ptconfig.toml`

is wrong. The second one should be `$HOME/.config/pt/config.toml`.

**Comment by StefanSchroeder** [comment]
Well, it would only be wrong if the author had claimed that the aforementioned spec was obeyed. :-| 
But I cannot find any reference to it. Nevertheless the use of $XDG_CONFIG_HOME seems to imply that the freedesktop specs are at least considered.
I am willing to contribute this trivial patch if @monochromegane agrees to this change, which might break the behavior for unaware users.
