### ISSUE TITLE
Can't find some file when using "-g"

### ISSUE THREAD

**Issue by jsfaint** [monochromegane/the_platinum_searcher#161]
pt version 2.1.4  
OS: CentOS 6.8 64bit

I try to find a linux module under the linux kernel source directory

But `pt -g` return nothing about that file
```
[root@nox linux]# pt -g "i915.ko"
```

I tried another file name, it do works
```
[root@nox linux]# pt -g "i915.c"
sound/pci/hda/hda_i915.c
drivers/gpu/drm/i915/i915_cmd_parser.c
```

And I tried find command, this file is exist
```
[root@nox linux]# find . | grep "i915.ko"
./drivers/gpu/drm/i915/i915.ko
./drivers/gpu/drm/i915/.i915.ko.cmd
```

This behavior is weird, and I don't know why 😢

**Comment by syohex** [comment]
Because `*.ko` is listed in `.gitignore`. File which is matched against `.gitignore` is not displayed. (This behavior is same as the silver searcher.)

**Comment by jsfaint** [comment]
@syohex got it, thanks 👍
