### ISSUE TITLE
Installation on spacemacs

### ISSUE THREAD

**Issue by zer09** [monochromegane/the_platinum_searcher#162]
I have no experience on emacs or vim and I want to try the spacemacs I already made it to install, and on the spacemacs guide it says it is better to install this. I already googled it but still I dont know how to install it.

Please help me, thanks

**Comment by syohex** [comment]
Please see https://github.com/monochromegane/the_platinum_searcher#user

1. Download archive(select by your platform) from https://github.com/monochromegane/the_platinum_searcher/releases 
2. Extract `pt`(or `pt.exe`) from archive
3. Put `pt` into the PATH directory

If you use macOS and use homebrew, you can install by `brew install pt`

**Comment by zer09** [comment]
Thanks a lot, I am able to install it, and try using command prompt and it works. But last question how i can use it using spacemacs? example I want to search something on project. I also try using the leader key SPC but cant find anything. BTW I am using windows 7.

**Comment by syohex** [comment]
You should ask this question to [spacemacs issue](https://github.com/syl20bnr/spacemacs/issues), not here.
