### ISSUE TITLE
When both -B and -C (before and context) are specified -B is ignored

### ISSUE THREAD

**Issue by Komosa** [monochromegane/the_platinum_searcher#163]
If I specify both -C and -B (or -A) only -C is used.
Instead both options should be combined.

example of current behavior:
`seq 4 | pt 3 -C1 -B2`
prints

    2
    3
    4

but should print

    1
    2
    3
    4

(grep prints expected output).

**Comment by syohex** [comment]
> (grep prints expected output).

This is only GNU grep behavior. BSD(macOS) grep, ack, the silver searcher, ripgrep behave same as the platinum searcher. In the first place, `-B` option conflicts with `-C` option. I think you should use `-A` option instead of `-C` if you specify `-B`.
