### ISSUE TITLE
[EXPIRED] Show only matching part

### ISSUE THREAD

**Issue by sergeevabc** [monochromegane/the_platinum_searcher#165]
Input
```
host -t A wikipedia.org | openssl dgst -sha256 | pt /N /e [A-Fa-f0-9]{64}
```
Output
```
(stdin)= 0d00409623da8ae039de83200af7f6fa9211bb13e1b3e10ea45142cd08b3e50b
```
Hash is coloured, but I need that coloured part only. How?

**Comment by sergeevabc** [comment]
Err… Helo?

**Comment by jschpp** [comment]
try `--nogroup`

**Comment by sergeevabc** [comment]
@jschpp, ```/nogroup``` is a shot in the dark since its stands for ```Don't print file name at header```.

**Comment by jschpp** [comment]
As far as I have seen not. And I'm sorry to give the nogroup option. I tested it on my mac and it worked. After testing it on linux I realized that macos omits the `(stdin)= ` part of the ssl digest

**Comment by sergeevabc** [comment]
Seems we are waiting for @monochromegane to implement it then.

**Comment by sergeevabc** [comment]
Is there anything a mere user like me could do to expedite a resolution of this issue?

**Comment by sergeevabc** [comment]
Six months passed. Err… Hello?

**Comment by sergeevabc** [comment]
@monochromegane, did you get a chance to look into this more thoroughly?
