### ISSUE TITLE
Context (-B or -A) is not displayed correctly if there are multiple matches

### ISSUE THREAD

**Issue by Komosa** [monochromegane/the_platinum_searcher#166]
`echo -e 'a1\nb\nc1' | pt 1 -B1` gives

    a1
    c1

but all three lines (of input) are expected as output:

    a1
    b
    c1

(grep gives expected output as well)

**Comment by syohex** [comment]
@komasa #167 has been merged. Could you check latest version ?

**Comment by Komosa** [comment]
Works for me. Thanks!
