### ISSUE TITLE
Options are different between Windows and Others.

### ISSUE THREAD

**Issue by kashewnuts** [monochromegane/the_platinum_searcher#173]
# Problems summary
Options are different between windows and Others.
- On Windows: `/g:`
- On Linux & macOS: `-g=`

## Env
- OS: Windows10 pro, Linux(Ubuntu16.04LTS), macOSX(Yosemite)
- pt: ver2.1.5

## Expected
I want you to unify the options between windows and Others, like `-g`.

## The reproduce ways

 1. Start cmd.exe or terminal
 2. Run `pt -h`

### Different command list
- after
- before
- color-match
- color-path
- context
- depth
- file-search-regexp
- g
- ignore
- output-encode
- vcs-ignore

### on Windows
![onwindows](https://cloud.githubusercontent.com/assets/1122795/22168952/e8f51ef0-dfb3-11e6-8491-15d2fed8aa86.png)

### on Linux
![onlinux](https://cloud.githubusercontent.com/assets/1122795/22168925/abbf64f0-dfb3-11e6-812d-83ad55683652.png)

**Comment by syohex** [comment]
This is github.com/jessevdk/go-flags specification

**Comment by kashewnuts** [comment]
I see. This is the specification of `go-flags`.

**Comment by vbauerster** [comment]
@kashewnuts you can use [this](https://github.com/svent/go-flags) fork of go-flags, to fix options in windows.
