### ISSUE TITLE
the `pt` command built by `go get -u` does nothing

### ISSUE THREAD

**Issue by jj1bdx** [monochromegane/the_platinum_searcher#177]
I might be wrong, but 
`go get -u github.com/monochromegane/the_platinum_searcher/...`
resulted in a `pt` command without doing anything.
I had to do
`go build -o pt cmd/pt/main.go`
instead to build a workable `pt` command in the source directory.
I'm not familiar with the golang yet, but I guess you need to add something for building a workable `pt` command with the `go get -u` command sequence.
The execution environment is based on FreeBSD 11.0-STABLE and Ports (go-1.8_1,1).

**Comment by monochromegane** [comment]
Thank you for reporting.
I try the `go get -u github.com/monochromegane/the_platinum_searcher/...`  on my macOS, and run successfully.

I don't have FreeBSD environment, so please execute the following commands, and tell me the output.

```
$ go install -v github.com/monochromegane/the_platinum_searcher/...
```

```
$ ls -l `which pt`
```

**Comment by jj1bdx** [comment]
@monochromegane 
`go install -v github.com/monochromegane/the_platinum_searcher/...`
generated no output.
And the ls command generates the following:
```shell
ls -l `which pt`
-rwx------  1 kenji  k2r  4362184 Apr  9 13:19 /home/kenji/golang/bin/pt*
```
BTW On FreeBSD the env variables are:
```shell
GOPATH=/home/kenji/golang
GOROOT=/usr/local/go
```

**Comment by monochromegane** [comment]
Thank you. It was reproduced on my environment.

```
$ go install -v github.com/monochromegane/the_platinum_searcher/...
github.com/monochromegane/the_platinum_searcher
github.com/monochromegane/the_platinum_searcher/cmd/pt
github.com/monochromegane/the_platinum_searcher/lib/pt

$ pt
$
```

In this case, `go install` put lib/pt to our bin directory. The lib/pt is C binding program, so nothing to do.
If `go install` choise cmd/pt after lib/pt, run scccessfully.

I will extract lib/pt (it's beta feature) from this repository.

**Comment by jj1bdx** [comment]
@monochromegane 

I think giving `lib/pt` an other name than `pt` will make things less confusing.

And I've also found the

>github.com/monochromegane/the_platinum_searcher
github.com/monochromegane/the_platinum_searcher/cmd/pt
github.com/monochromegane/the_platinum_searcher/lib/pt

sequence was followed in the `go test` command.

I'll stick to the `go build -o pt cmd/pt/main.go` for the time being.

**Comment by monochromegane** [comment]
> I think giving lib/pt an other name than pt will make things less confusing.

Yes, but I thought it was not good to install the unuse command (only C binding binary) when go get pt. So, I remove lib/pt from this repo.

**Comment by jj1bdx** [comment]
@monochromegane Fair enough. Thx for checking this out! :)

**Comment by jj1bdx** [comment]
@monochromegane Rebuilding https://github.com/monochromegane/the_platinum_searcher/commit/c7d8eec66dca50773e6b4ee7dfdad2174860b9b1 with `go get -u` solved the issue. Thx a lot!
