### ISSUE TITLE
How to stop pt interpreting pattern as flags. E.g, pt "-v" , I actually want to search for the string "-v"

### ISSUE THREAD

**Issue by fritz-quandoo** [monochromegane/the_platinum_searcher#206]
Hi, thanks for the great tool

I am looking for the actual string '-v' in some bash scripts.

If I run `pt "-v"` (any combination of slashes and quotation marks), pt will complain with `unknown flag `v'`. How do I work around it? thanks

**Comment by panchoh** [comment]
Hi!

Try this:

$ pt -- -v

Hope that it helps.

Cheers,

-- 
pancho horrillo

**Comment by fritz-quandoo** [comment]
Brilliant, it works, thanks a lot
