### ISSUE TITLE
--ignore regexp not handling '#' as expected

### ISSUE THREAD

**Issue by sdsmith** [monochromegane/the_platinum_searcher#208]
I'm trying to pass `--ignore="#.*#` to pt from the command line. It doesn't seem to recognize hashtags (`#`) as characters during matching.

I have tried escaping with single, double, and triple back slashes (`\`).
`.*` matches correctly. `#.*` does not.

Tested in a directory that contained the following files:
- abc
- #abc
- abc#
- #abc#

**Comment by syohex** [comment]
FYI you can write it like `--ignore=[#].*#`

**Comment by sdsmith** [comment]
`--ignore=[#].*#` also doesn't work:

```
ζ pt --smart-case -e --nogroup --color --ignore='[#].*#' -- hey
./abc:1:hey
./#abc:1:hey
./abc#:1:hey
./#abc#:1:hey
```

**Comment by syohex** [comment]
Ah, sorry it should be write `--ignore=[#]*#`. It is not a regular expression, shell glob pattern. BTW go-ignore issue is already fixed so I suppose you can write `--ignore=\#*#` after updating `go-ignore` and rebuilding the platinum searcher.

**Comment by sdsmith** [comment]
The `[#]*#` pattern works perfect. I didn't realize it was a shell glob pattern. Thank you!
