### ISSUE TITLE
Support .ptignore file (like .agignore) for patterns to be ignored independent of version control

### ISSUE THREAD

**Issue by shantanugoel** [monochromegane/the_platinum_searcher#25]
ag supports a .agignore file in user's home directory for global ignore patterns. Please see if this can be supported

**Comment by abourget** [comment]
It would seem that the .ptignore support was shrinked in the v2 rewrite (if I'm reading the history correctly).

I'd like to have per-project `.ptignore` and also per-directory `.ptignore` files.. that would behave just like `.gitignore` files. I could drop a `.ptignore` in a directory, and `pt` wouldn't touch the files listed in there.

Right now.. I don't have a simple way (when integrated into Emacs, meaning cross-projects) to invoke `pt` ignoring certain directories.
