### ISSUE TITLE
color disappears when piping

### ISSUE THREAD

**Issue by RickyS** [monochromegane/the_platinum_searcher#40]
Searching for word 'title' in my source code.

**pt --color title | less**
or
**pt --color --file-search-regexp='\.go$'  | less**

The color does not appear.  Color appears when **not piped**. It isn't less, it's the pipe.  Color is _also gone_ in the case of:
**pt --color title | cat**

 -- 
Description:    Ubuntu 14.04 LTS
Codename:       trusty
Linux sda8 3.13.0-29-generic #53-Ubuntu SMP Wed Jun 4 21:00:20 UTC 2014 x86_64 GNU/Linux
jessie/sid

$ pt --version
1.6.2

**Comment by kergoth** [comment]
Afaict this its broken in 2.1.0, making it impossible to get colored, grouped, paged output. It'd be nice for either explicit --color to force color on even when piped, or add a force color option.

**Comment by district10** [comment]
`ag` has a `--pager` option, so we can use `ag --pager=less KEYWORD`.
