### ISSUE TITLE
Windows 上での PATH 区切り文字の表示

### ISSUE THREAD

**Issue by lurdan** [monochromegane/the_platinum_searcher#67]
結果出力時に、ファイル名の PATH を Windows のお作法にのっとって \ で表示されていると
辛い場面があるので、/ で置き換えて出力してくれるオプションを追加して頂けないでしょうか。

**Comment by vermiculus** [comment]
While `pt` aims to support searching text in all sorts of languages, I think the developers would appreciate features being requested in English :smile:

**Comment by lurdan** [comment]
@vermiculus 
"It would be nice to have the option which could switch path separators (windows style <> unix/cygwin style) in search results output."

Anyway, closing this issue because I've already given up using pt, and there's no interested party other than me. Thank you for taking care this abondoned issue!

**Comment by vermiculus** [comment]
@lurdan You are *hardly* the only interested party – this is a good idea!
