### ISSUE TITLE
[Request] Add a way to filter files by its size. ファイルサイズによるフィルタリング機能

### ISSUE THREAD

**Issue by lambdalisue** [monochromegane/the_platinum_searcher#77]
はじめまして、便利に利用させていただいています。有末と申します。

個人的な機能要望で恐縮なのですが、ファイルサイズによるフィルタリングに対応していただけると非常に助かります。これというのも仕事の関係上数十ＧBに至るファイル（バイナリの場合もASCIIの場合もあります）が混在したディレクトリから検索を行うことが多いのですが、そのようなファイルの内容を検索しに行くと非常に時間がかかってしまうためです。
 `--ignore` などのオプションで全てを指定しても構わないのですが、種類が多いため「あるサイズ以上のファイルを検索しない」というオプションの指定が可能だととても便利です。

お時間があるときで構いませんのでご一考いただけたら幸いです。

**Comment by vermiculus** [comment]
While `pt` aims to support searching text in all sorts of languages, I think the developers would appreciate features being requested in English :smile:

**Comment by StefanSchroeder** [comment]
While adding a size-filter to pt is absolutely possible, I feel that it would be an unnecessary feature given the omnipresence of 'find':

Try this. This will look for "Waldo" in all files bigger than 1k and smaller than 3k.

find  ~ -type f -size '+1k' -a  -size '-3k' -exec pt Waldo '{}' ';'


http://stackoverflow.com/questions/13882081/gnu-find-test-for-file-size-greater-smaller-equal-a-certain-size

I suggest to 'reject' this issue.

**Comment by lambdalisue** [comment]
@StefanSchroeder 
Using `find` is more flexible and I agree with your opinion in that point but things become more simple if `pt` itself has an option for that.
For example, I used to use `pt` in [unite.vim](https://github.com/Shougo/unite.vim) and it is a bit difficult to configure while I don't always want to limit the candidate with its size.

But anyway, I don't use `pt` recently so I close this issue.
