### ISSUE TITLE
Doesn't hit dot files

### ISSUE THREAD

**Issue by slowkin** [monochromegane/the_platinum_searcher#83]
<pre>
# Doesn't hit dot files  
  
## same text in file  
htaccess  
.htaccess  
-----  
AuthGroupFile "/dev/null"  
-----  
  
## execute  
pt --nogroup --nocolor --ignore-case --smart-case --depth 99 -e "AuthGroupFile" .  
-----  
htaccess:1:AuthGroupFile "/dev/null"  
-----  
Doesn't hit .htaccess  
I hope .htaccess hit default or option please!  
  
pt --version  
1.7.6  
</pre>

**Comment by syohex** [comment]
You can use `--hidden` or `-H` option for this purpose.

**Comment by slowkin** [comment]
<pre>
Thanks for reply @syohex .

I understand and try command follow.
pt --nogroup --nocolor --ignore-case --smart-case --depth 99 --hidden -e "AuthGroupFile" .
-----
unknown flag `hidden'
-----
Oh, my God. TT

# Environment
Windows 7 Professional
cmd.exe
pt_windows_amd64.zip

different in understanding? or version difference?? ...
I check pt --help, don't show --hidden option TT

thank you.
</pre>

**Comment by syohex** [comment]
Ah, `hidden` option can be used only in development version.
If you use binary version, you cannot use it now.

You need to build `pt` from source code for using `--hidden` option.

**Comment by slowkin** [comment]
Thanks syohex.

found --hidden option in branch!!!

TNKU.^^
