### ISSUE TITLE
Implement a verbose --version with the name of the application

### ISSUE THREAD

**Issue by syl20bnr** [monochromegane/the_platinum_searcher#84]
Since `pt` can shadow the `pt` command line tool of TCL [parser tools](https://core.tcl.tk/tcllib/doc/trunk/embedded/www/tcllib/files/apps/pt.html) we need a way to identify the platinum searcher. The current `--version` only prints the version without the name of the application and the help screen does not include the name of the application (with homebrew version at least).

I propose to either put the application name in the help or simply put the application name in the `--version` output.

**Comment by monochromegane** [comment]
pt v2.0.0 has released, the pt print version like the following :^)

```
pt version 2.0.0
```
