### ISSUE TITLE
.gitignore Globstar Not Respected

### ISSUE THREAD

**Issue by tscheffe** [monochromegane/the_platinum_searcher#87]
"_It ignores file patterns from your .gitignore_" feature from the Readme is incomplete.

If I have the files
- `components/something/vendor-a/tags`
- `components/vendor-b/tags`

and in my `.gitignore` i have `components/**/tag`. Those files are not ignored, as expected. Git does ignore them.

I had to replace the globstar option in my `.gitignore` with `components/*/tags` and `components/*/*/tags` which is less ideal.

On Globstar, heres the [Gnu manual info](http://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html) with quote:

> If set, the pattern '**' used in a filename expansion context will match all files and zero or more directories and subdirectories. If the pattern is followed by a '/', only directories and subdirectories match.

**Comment by cazador481** [comment]
https://github.com/mattn/go-zglob implements globstar pattern matching.

**Comment by rosshadden** [comment]
This also means the following gitignore pattern, which is recommended by people on the Internet for ignoring generated (extensionless) binary files, is not used correctly:

```
*
!/**/
!*.*
```

Based on @tscheffe's post, I tried adding these, which made pt work as expected, though is pretty sloppy and not scalable:

```
!/*/*/
!/*/*/*/
```
