### ISSUE TITLE
How to do escape in regex PATTERN?

### ISSUE THREAD

**Issue by leesei** [monochromegane/the_platinum_searcher#94]
I would like to search for `sort` function call case insensitively in my code.
This does not work:
```sh
$ pt -i sort\(
error parsing regexp: missing closing ): `(?i)(sort()`
```

`pt sort\(` works correctly for small letter case, but I would like to search case insensitively.
`-i` causes `pt` to use regex.

```sh
$ pt --version
1.7.4
``

Related to #62.

**Comment by syohex** [comment]
Backslash is removed by shell. You should quote pattern as below.

```bash
$ pt 'sort\('
```

**Comment by leesei** [comment]
Actually I've tried all sorts of escape to my knowledge.

```sh
$ grep -rn sort\( | head
lib/plugins/generator/post.js:6:  var posts = locals.posts.sort('-date').toArray();
lib/plugins/console/list/tag.js:11:  var data = Tag.sort({name: 1}).map(function(tag){
lib/plugins/console/list/post.js:11:  var data = Post.sort({published: -1, date: 1}).map(function(post){
lib/plugins/console/list/route.js:7:  var routes = this.route.list().sort();
lib/plugins/console/list/page.js:11:  var data = Page.sort({date: 1}).map(function(page){
lib/plugins/console/help.js:67:  list.sort(function(a, b){
lib/plugins/helper/list_categories.js:35:    return categories.find(query).sort(orderby, order).filter(function(cat){
lib/plugins/helper/tagcloud.js:193:    tags = tags.sort(orderby, order);
lib/plugins/helper/tagcloud.js:208:  tags.sort('length').forEach(function(tag){
lib/plugins/helper/list_posts.js:23:  posts = posts.sort(orderby, order);

$ pt 'sort\('   
# no result
```

**Comment by syohex** [comment]
Ah  you need not to escape parenthesis.

```
% pt 'sort('
```

I enable regexp flag, sorry.

**Comment by leesei** [comment]
```sh
$ pt 'sort('
error parsing regexp: missing closing ): `(?i)(sort()`
```

`'sort(`' and `sort\(` should be the same thing.
I want to pass an escape into Go, which *should* be `'sort\('` I suppose (I'm not familiar with Go's regex).

**Comment by syohex** [comment]
Regexp search is disabled as default so pattern is used as string as default. Do you set any alias which sets `-e` option ? I can reproduce your issue with `-e` option.

```
$ ./pt_linux_amd64/pt -e 'sort('
error parsing regexp: missing closing ): `(sort()`
```

However I cannot reproduce your issue without `-e` option.

```
$ ./pt_linux_amd64/pt 'sort('   
hoge.txt:
1:sort()
2:sort(adajsdofijasiodfjadf)
3:sort(aidjfaoidjfaiodj)
```

I test with version 1.7.7 binary.

```
% ./pt_linux_amd64/pt --version
1.7.7
```

**Comment by leesei** [comment]
@syohex Thanks, I used `-i` by default and that will trigger regex pattern as seen from my error.
Without `-i` I am able to get search result. I'll update my question to reflect this.

**Comment by syohex** [comment]
I cannot get such error only with `-i` option.

```
./pt_linux_amd64/pt -i 'sort('
hoge.txt:
1:sort()
2:sort(apples)
3:sort(oranges)
```

I can get the error by setting `-e` option too.
```
% ./pt_linux_amd64/pt -ei 'sort('
error parsing regexp: missing closing ): `(?i)(sort()`
```
I suppose you may set `-e` option. If regular expression flag is enabled, parenthesis means match group and they should be pair. If you want to match parenthesis, you should escape it as below.

```
% pt -ie 'sort\('
```

**Comment by leesei** [comment]
I noticed I was using 1.7.4.
I updated to 1.7.7 and the behavior is as you mentioned.
Thanks all.

I also corrected my previous comment.
