### ISSUE TITLE
regexp not working on windows

### ISSUE THREAD

**Issue by albfan** [monochromegane/the_platinum_searcher#96]
I'm trying to do a regexp search "a|b" (say foo|bar)

This is a simple failed test:

    C:\some\dir> pt --version
    1.7.7
    C:\some\dir> echo a > test
    C:\some\dir> echo b >> test
    C:\some\dir> echo a^|b >> test
    C:\some\dir> echo a\^|b >> test
    C:\some\dir> cat test
    a
    b
    a|b
    a\|b
    C:\some\dir> pt "a|b" test
    test:
    3:a|b
	C:\some\dir> pt a^|b test
    test:
    3:a|b
    C:\some\dir> pt "a\|b" test
    test:
    4:a\|b
    C:\some\dir> pt a\^|b test
    test:
    4:a\|b

As expected:

    C:\some\dir> pt a test
    test:
    1:a
    3:a|b
    4:a\|b

works

**Comment by syohex** [comment]
Regular expression search is disabled as default. You should add `-e` option for regular expression search.

**Comment by albfan** [comment]
Of course. Thanks!
