### ISSUE TITLE
Count option?

### ISSUE THREAD

**Issue by jungle-boogie** [monochromegane/the_platinum_searcher#99]
Hello,

Ack supports a count option very simply:

     % ack -c foo
    pt_20150801.csv:6732
    foo.csv:6732

Will you consider supporting a count option?

**Comment by justinmk** [comment]
https://github.com/monochromegane/the_platinum_searcher/pull/79

**Comment by jungle-boogie** [comment]
Hi,

> --column option already exists. #79

Is there a method to have it more ack/grep like where it can get a total at the end of the file? grep and ack have the same `-c` to count number of occurrences. 

    pt foo foo.csv | wc -l
    6732

I can do it like above but that's kind of cheapening the speed of pt. 

    % time pt foo foo.csv | time wc -l
    6732
        0.52 real         0.00 user         0.02 sys
    pt foo foo.csv  0.04s user 0.03s system 13% cpu 0.536 total
    time wc -l  0.01s user 0.02s system 5% cpu 0.535 total


    % time ack -c foo foo.csv
    6732
    ack -c foo foo.csv  0.03s user 0.01s system 18% cpu 0.217 total

**Comment by monochromegane** [comment]
This option is implemented by @syohex . Please check it, thanks.
